name: .NET

on:
  workflow_dispatch:
  push:
    branches: 
      - release

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: "amd64"
            rid: "linux-musl-x64"
          - arch: "aarch64 "
            rid: "linux-musl-arm64"
          - arch: "armv7"
            rid: "linux-musl-arm"
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: build_release
      run: |
        cd src
        dotnet publish -r ${{ matrix.rid }} --configuration Release --self-contained -o build/